Repository hpi-swt2/bookkeeper-portal-red, pull requests merged in 2023-01, with the labels that each got.

#141 Cl/reserve items
  .idea/bookkeeper-portal-red.iml
  .idea/workspace.xml
  app/components/item_availability_badge_component.rb
  app/components/item_borrow_button.html.erb
  app/components/item_borrow_button.rb
  app/controllers/items_controller.rb
  app/models/item.rb
  app/views/items/_book_form.html.erb
  app/views/items/_form.html.erb
  app/views/items/_game_form.html.erb
  app/views/items/_item_largescreen.html.erb
  app/views/items/_item_smallscreen.html.erb
  app/views/items/_movie_form.html.erb
  app/views/items/_other_form.html.erb
  config/locales/views/landing_page/de.yml
  config/locales/views/landing_page/en.yml
  config/routes.rb
  db/migrate/20221214130227_add_max_reservation_days.rb
  db/migrate/20230105110905_set_default_max_borrowing_days.rb
  db/schema.rb
  spec/factories/items.rb
  spec/features/items/edit_spec.rb
  spec/features/items/new_spec.rb
  spec/features/items/reservation_spec.rb
  spec/features/items/show_spec.rb
  spec/models/item_spec.rb
  spec/requests/items_spec.rb
  spec/views/items/edit.html.erb_spec.rb
  spec/views/items/index.html.erb_spec.rb
  spec/views/items/new.html.erb_spec.rb
  spec/views/items/show.html.erb_spec.rb
  spec/views/landing_page/landing_page_spec.rb
Labels: feature

#213 fix: use uniform time datatypes
  app/controllers/items_controller.rb
  app/mailers/notification_mailer.rb
Labels: refactoring

#267 fix: add missing mail to link
  app/assets/stylesheets/application.scss
  app/views/groups/edit.html.erb
Labels: bug

#364 Rename personal groups after their member
  app/models/user.rb
  db/migrate/20230120094018_rename_personal_groups_to_member_name.rb
  spec/models/user_spec.rb
Labels: feature
